src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_growth_Indicator__c</fullName>
        <label>Account growth Indicator</label>
        <picklist>
            <picklistValues>
                <fullName>Fast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Median</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Annual_Revenue__c</fullName>
        <label>Annual Revenue</label>
        <summarizedField>Account_Plan__c.Annual_Revenue__c</summarizedField>
        <summaryFilterItems>
            <field>Account_Plan__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>Account_Plan__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Average_Outstanding__c</fullName>
        <label>Average Outstanding</label>
        <summarizedField>Account_Plan__c.Average_Outstanding__c</summarizedField>
        <summaryFilterItems>
            <field>Account_Plan__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>Account_Plan__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Commitment_Amount__c</fullName>
        <label>Commitment Amount</label>
        <summarizedField>Account_Plan__c.Commitment_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Account_Plan__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>Account_Plan__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Company_Growth_Indicator__c</fullName>
        <label>Company Growth Indicator</label>
        <picklist>
            <picklistValues>
                <fullName>High Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low growth</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>IF(LEN(BillingState)=0, &quot;None&quot;,
IF(CONTAINS(&quot;AK:AZ:CA:CO:HA:ID:KS:MT:NV:NM:OK:OR:TX:UT:WA:WY&quot;, BillingState), &quot;West&quot;,
IF(CONTAINS(&quot;CT:ME:MA:NH:NY:PA:RI:VT&quot;, BillingState), &quot;East&quot;,
IF(CONTAINS(&quot;AL:AR:DC:DE:FL:GA:KY:LA:MD:MS:NC:NJ:SC:TN:VA:WV&quot;, BillingState), &quot;South&quot;,
IF(CONTAINS(&quot;IL:IN:IA:MI:MN:MO:NE:ND:OH:SD:WI&quot;, BillingState), &quot;North&quot;, &quot;Unknown&quot;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retention_Risk__c</fullName>
        <label>Retention Risk</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Risk_Factor__c</fullName>
        <label>Risk Factor</label>
        <picklist>
            <picklistValues>
                <fullName>Large Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint to RM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M&amp;A activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tenure__c</fullName>
        <formula>IF(
    NOT(ISNULL(CreatedDate)), /* Condition */
    TEXT(FLOOR((NOW()-CreatedDate)/365.2425)) &amp; &quot; year(s) &quot; &amp;
    TEXT(FLOOR(MOD((NOW()-CreatedDate),365.2425)/30)) &amp; &quot; month(s) &quot; &amp;
    TEXT(FLOOR(MOD((NOW()-CreatedDate),30))) &amp; &quot; days(s) &quot; , /* Value IF True */
    &quot;&quot; /* Value IF False */
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tenure</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account Plan</description>
        <inlineHelpText>Account Plan</inlineHelpText>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>All_In_Drawn_Spread_LIBOR_Spread_Faci__c</fullName>
        <description>All-In Drawn Spread (LIBOR Spread + Facility Fee)</description>
        <inlineHelpText>All-In Drawn Spread (LIBOR Spread + Facility Fee)</inlineHelpText>
        <label>All-In Drawn Spread (LIBOR Spread + Faci</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Annual_Revenue__c</fullName>
        <description>Annual Revenue</description>
        <inlineHelpText>Annual Revenue</inlineHelpText>
        <label>Annual Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Outstanding__c</fullName>
        <description>Average Outstanding</description>
        <inlineHelpText>Average Outstanding</inlineHelpText>
        <label>Average Outstanding</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commitment_Amount__c</fullName>
        <description>Commitment Amount</description>
        <inlineHelpText>Commitment Amount</inlineHelpText>
        <label>Commitment Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Execution_What_we_Know__c</fullName>
        <label>What we Know</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Execution_What_we_Need_to_Know__c</fullName>
        <label>What We Need to Know</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Obstacles_What_We_Know__c</fullName>
        <label>What We Know</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Obstacles_What_we_Need_to_Know__c</fullName>
        <label>What We Need to Know</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ROEC_Return_on_Economic_Capital__c</fullName>
        <description>ROEC (Return on Economic Capital)</description>
        <inlineHelpText>ROEC (Return on Economic Capital)</inlineHelpText>
        <label>ROEC (Return on Economic Capital)</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>RORC_Return_on_Regulatory_Capital__c</fullName>
        <description>RORC (Return on Regulatory Capital)</description>
        <inlineHelpText>RORC (Return on Regulatory Capital)</inlineHelpText>
        <label>RORC (Return on Regulatory Capital)</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Results_What_we_Need_to_Know__c</fullName>
        <description>What we Need to Know(Results)</description>
        <inlineHelpText>What we Need to Know(Results)</inlineHelpText>
        <label>What We Need to Know</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Results_What_we_know__c</fullName>
        <description>What we know (Results)</description>
        <inlineHelpText>What we know (Results)</inlineHelpText>
        <label>What We know</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Need_Analysis__c.object
<CustomObject>
    <description>Customer Need Analysis</description>
    <fields>
        <fullName>Actual_Revenue__c</fullName>
        <description>Actual Revenue</description>
        <inlineHelpText>Actual Revenue</inlineHelpText>
        <label>Actual Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Future_Opportunity__c</fullName>
        <label>Future Opportunity?</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Name_X__c</fullName>
        <label>Product Name</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Customer Need Analysis</relationshipLabel>
        <relationshipName>Customer_Need_Analysis</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Provider__c</fullName>
        <description>Service Provider</description>
        <label>Service Provider</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Services_Used__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Services Used</description>
        <inlineHelpText>Services Used</inlineHelpText>
        <label>Services Used</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_of_Wallet_estimate__c</fullName>
        <label>Share of Wallet estimate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Need Analysis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Obligation__c.object
<CustomObject>
    <description>List all customer obligations like loan, credit card, letter of credit</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Obligations</relationshipLabel>
        <relationshipName>Obligations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Obligation</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Obligation Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Obligations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>TODAY() - Stage_changed_date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Age__c</fullName>
        <formula>TODAY()-DATEVALUE(CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AccountPlanController.cls
public class AccountPlanController {
    public Account account{get;set;}
    public Account_Plan__c accountPlan{get;set;}
    public List<Case> listCase{get;set;}
    public List<Event> listMeeting{get;set;}
    public List<Task> listTask{get;set;}
    public List<Opportunity> listOpportunity{get;set;}
    public List<Account_Plan__c> listAccountPlan{get;set;}
    public List<Contact> listContact{get;set;}
    public List<Customer_Need_Analysis__c> listNeedAnalysis{get;set;}
    public List<Value_Alignment__c> listValueAlignment{get;set;}
    public List<Action_Plan__c> listActionPlan{get;set;}
    public List<AccountTeamMember> listAccountTeamMember{get;set;}
    public List<Next_Best_Product__c> listNextBestProduct{get;set;}
    public List<Deposit__c> listDeposit{get;set;}
    public List<Obligation__c> listDerivative{get;set;}
    public List<Obligation__c> listFX{get;set;}
    public List<Obligation__c> listCreditCard{get;set;}
    public String parentMeetingId{get;set;}
    public Call_Notes__c callNote{get;set;}
    public String meetingName{get;set;}
    public String meetingDateTime{get;set;}
    public List<Call_Notes__c> listCallNotes{get;set;}
    
    public double committmentAmount{get;set;}
    public double averageOutStanding{get;set;}
    public double annualRevenue{get;set;}
    public double allInDrawnSpread{get;set;}
    public double roec{get;set;}
    public double rorc{get;set;}
    public string data1{get;set;}
    public string data2{get;set;}
    String accountId ;
    public Id actPlanId{get;set;}
    public string address{get;set;}
    
    public double annualR {get;set;}
    public string CompanyGrowthIndicator {get;set;}
    public string AccountgrowthIndicator {get;set;}
    
    public class OpportunityWrapper{
        public Opportunity opp{get;set;}
        public string trend{get;set;}
    }
    
    public AccountPlanController(ApexPages.StandardController std){
        String urlString = ApexPages.currentPage().getURL();
        system.debug('urlString==============='+urlString);
        actPlanId = std.getId();
        accountId = ApexPages.currentPage().getParameters().get('accountId');
        //set accountid back after refresh
        if(!String.isEmpty(actPlanId))
            accountId = [select account__c from account_plan__c where id = :actPlanId].account__c;
        if(accountId != null){
            account = [SELECT Id,Name,Region__c,Industry,Tenure__c,AnnualRevenue,Parent.Name, CreatedDate, retention_risk__c, risk_factor__c,
                       Phone, BillingStreet, BillingCity, BillingState, BillingPostalCode,Company_Growth_Indicator__c,Account_growth_Indicator__c,
                       BillingCountry,Website, account.owner.firstName
                       from Account where Id=: accountId]; 
            
            address = ' ' + account.BillingStreet + ', ' + 
                account.BillingCity+', ' + account.BillingState + ' ' +account.BillingPostalCode;
            
            listOpportunity = [select Id, Name, Amount,Amount__c, StageName,ExpectedRevenue,CloseDate,CreatedDate,LastModifiedDate,Age__c,Opportunity_Age__c from Opportunity where AccountId =: accountId
                          order by CloseDate desc];
            listContact = [select Id, Name,Salutation, FirstName, LastName, Phone, Email, Title FROM contact where AccountId =: accountId
                           order by LastName asc];
            listMeeting = [select Id, Subject, StartDateTime,ActivityDateTime,Description,DurationInMinutes,
                           Call_Notes__c from Event where WhatId =: accountId and StartDateTime >= Today
                           order by StartDateTime asc];
            listTask = [select Id, Subject, Status,ActivityDate from Task where WhatId =: accountId and ActivityDate >= today order by ActivityDate asc];
        }
        if(actPlanId != null){
            accountPlan = [select Id, Name , Account__c, Results_What_we_know__c, 
                           Results_What_we_Need_to_Know__c, Obstacles_What_We_Know__c, 
                           Obstacles_What_we_Need_to_Know__c, Execution_What_we_Know__c,
                           Execution_What_we_Need_to_Know__c, Annual_Revenue__c, Average_Outstanding__c, ROEC_Return_on_Economic_Capital__c,
                           RORC_Return_on_Regulatory_Capital__c,All_In_Drawn_Spread_LIBOR_Spread_Faci__c,
                           Commitment_Amount__c from Account_Plan__c where Id =: actPlanId limit 1];
            
            listNeedAnalysis = [select Id, Name, Product_Name_X__r.Name, Service_Provider__c, Services_Used__c,
                                Actual_Revenue__c, Future_Opportunity__c, Share_of_Wallet_estimate__c, RM_Estimate__c, Comments__c from 
                                Customer_Need_Analysis__c where Product_Name_X__c =: actPlanId];
            
            listValueAlignment = [select Id, Name , Corp_Finance_M_A__c, Global_Markets_FX_IRD__c, Price__c, Structure__c,Competitor__c,
                                  Treasury__c, Value_Name__c from Value_Alignment__c where  Value_Name__c =: actPlanId];
            listNextBestProduct = [select Id, Name, Proposed_Date_of_Offer__c, Status__c from Next_Best_Product__c where 
                                   Account_Name__c =: accountId ];
            
            data1 = '';
            data2 = '';
            if(listValueAlignment.size() > 0){
                data1 = listValueAlignment[0].Treasury__c + ',' + listValueAlignment[0].Price__c + ',' + listValueAlignment[0].Structure__c + ',' + listValueAlignment[0].Corp_Finance_M_A__c + ',' + listValueAlignment[0].Global_Markets_FX_IRD__c;
                if(listValueAlignment.size() > 1)
                    data2 = listValueAlignment[1].Treasury__c + ',' + listValueAlignment[1].Price__c + ',' + listValueAlignment[1].Structure__c + ',' + listValueAlignment[1].Corp_Finance_M_A__c + ',' + listValueAlignment[1].Global_Markets_FX_IRD__c;
            }
            listActionPlan = [select  Id,Responsible_Team_Member__c, Timing__c from Action_Plan__c where  Account_Plan_NameX__c =: actPlanId];
        }
        else{
            accountPlan = new Account_Plan__c();
            accountPlan.Account__c = accountId;
            listActionPlan = new List<Action_Plan__c>();
            listValueAlignment = new List<Value_Alignment__c>();
            listNeedAnalysis = new List<Customer_Need_Analysis__c>();            
        }
        
        listAccountPlan = [select Id, Annual_Revenue__c, Average_Outstanding__c, ROEC_Return_on_Economic_Capital__c,
                           RORC_Return_on_Regulatory_Capital__c,All_In_Drawn_Spread_LIBOR_Spread_Faci__c,
                           Commitment_Amount__c from Account_Plan__c where Account__c =: accountId];
        
        committmentAmount = 0;
        averageOutStanding = 0;
        annualRevenue = 0;
        allInDrawnSpread = 0;
        roec = 0;
        rorc = 0;
        
        annualR= 0;
        CompanyGrowthIndicator  ='';
        AccountgrowthIndicator ='';
        
        
        if(account.AnnualRevenue !=null) {
            annualR= (account.AnnualRevenue)/1000000;
        }
        if(account.Company_Growth_Indicator__c !=null) {    
            CompanyGrowthIndicator  = account.Company_Growth_Indicator__c;
        }
        if(account.Account_growth_Indicator__c !=null) {    
            AccountgrowthIndicator = account.Account_growth_Indicator__c;
        }    
        
        for(Account_Plan__c accountPlan : listAccountPlan){
            if(accountPlan.Commitment_Amount__c > 0)
                committmentAmount += accountPlan.Commitment_Amount__c;
            if(accountPlan.Average_Outstanding__c > 0)
                //averageOutStanding += accountPlan.Average_Outstanding__c;
            if(accountPlan.Annual_Revenue__c > 0)
                //annualRevenue  += accountPlan.Annual_Revenue__c;
            if(accountPlan.All_In_Drawn_Spread_LIBOR_Spread_Faci__c > 0)
                allInDrawnSpread += accountPlan.All_In_Drawn_Spread_LIBOR_Spread_Faci__c;
            if(accountPlan.ROEC_Return_on_Economic_Capital__c > 0)
                roec += accountPlan.ROEC_Return_on_Economic_Capital__c;
            if(accountPlan.RORC_Return_on_Regulatory_Capital__c > 0)
                rorc += accountPlan.RORC_Return_on_Regulatory_Capital__c;
        }
        for(Opportunity opp : listOpportunity){
            if(Opp.StageName == 'Closed Won')
                averageOutStanding += Opp.Amount__c; 
            if(Opp.StageName != 'Closed Won' && Opp.StageName != 'Closed Lost')
            annualRevenue +=Opp.Amount__c; 
        }
    }
    
    public pageReference SaveAccountPlan(){
        upsert accountPlan;
        return new Pagereference('/'+accountId);
    }
    public void showCallNoteModal()
    {
        callNote = new Call_Notes__c();
        callNote.Activity_Id__c = parentMeetingId;
    }
    public void createCallNote()
    {
        insert callNote;
    }
    public pageReference Cancel(){
        return new Pagereference('/'+accountId);
    }
    public void addAnalysisToList(){
        system.debug('added=================');
        listNeedAnalysis = [select Id, Name, Product_Name_X__r.Name, Service_Provider__c, Services_Used__c,
                            Actual_Revenue__c, Future_Opportunity__c, Share_of_Wallet_estimate__c, RM_Estimate__c, Comments__c from 
                            Customer_Need_Analysis__c where Product_Name_X__c =: actPlanId];
    }
}