src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Annual_Revenue__c</fullName>
        <label>Annual Revenue</label>
        <summarizedField>Account_Plan__c.Annual_Revenue__c</summarizedField>
        <summaryFilterItems>
            <field>Account_Plan__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>Account_Plan__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Average_Outstanding__c</fullName>
        <label>Average Outstanding</label>
        <summarizedField>Account_Plan__c.Average_Outstanding__c</summarizedField>
        <summaryFilterItems>
            <field>Account_Plan__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>Account_Plan__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Commitment_Amount__c</fullName>
        <label>Commitment Amount</label>
        <summarizedField>Account_Plan__c.Commitment_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Account_Plan__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>Account_Plan__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account Plan</description>
        <inlineHelpText>Account Plan</inlineHelpText>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>All_In_Drawn_Spread_LIBOR_Spread_Faci__c</fullName>
        <description>All-In Drawn Spread (LIBOR Spread + Facility Fee)</description>
        <inlineHelpText>All-In Drawn Spread (LIBOR Spread + Facility Fee)</inlineHelpText>
        <label>All-In Drawn Spread (LIBOR Spread + Faci</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Annual_Revenue__c</fullName>
        <description>Annual Revenue</description>
        <inlineHelpText>Annual Revenue</inlineHelpText>
        <label>Annual Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Outstanding__c</fullName>
        <description>Average Outstanding</description>
        <inlineHelpText>Average Outstanding</inlineHelpText>
        <label>Average Outstanding</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commitment_Amount__c</fullName>
        <description>Commitment Amount</description>
        <inlineHelpText>Commitment Amount</inlineHelpText>
        <label>Commitment Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ROEC_Return_on_Economic_Capital__c</fullName>
        <description>ROEC (Return on Economic Capital)</description>
        <inlineHelpText>ROEC (Return on Economic Capital)</inlineHelpText>
        <label>ROEC (Return on Economic Capital)</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>RORC_Return_on_Regulatory_Capital__c</fullName>
        <description>RORC (Return on Regulatory Capital)</description>
        <inlineHelpText>RORC (Return on Regulatory Capital)</inlineHelpText>
        <label>RORC (Return on Regulatory Capital)</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Need_Analysis__c.object
<CustomObject>
    <description>Customer Need Analysis</description>
    <fields>
        <fullName>Actual_Revenue__c</fullName>
        <description>Actual Revenue</description>
        <inlineHelpText>Actual Revenue</inlineHelpText>
        <label>Actual Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Future_Opportunity__c</fullName>
        <label>Future Opportunity?</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opportunity Created?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Name_X__c</fullName>
        <label>Product Name</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Customer Need Analysis</relationshipLabel>
        <relationshipName>Customer_Need_Analysis</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RM_Estimate__c</fullName>
        <description>RM Estimate</description>
        <label>RM Estimate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Provider__c</fullName>
        <description>Service Provider</description>
        <label>Service Provider</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Services_Used__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Services Used</description>
        <inlineHelpText>Services Used</inlineHelpText>
        <label>Services Used</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_of_Wallet_estimate__c</fullName>
        <label>Share of Wallet estimate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Need Analysis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_date__c</fullName>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Derivatives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cards</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/HandlerCreateOpportunities.cls
public with sharing class HandlerCreateOpportunities implements BotHandler {
    
    public BotResponse handle(String utterance, String[] params, Map<String, String> session) {
        //Integer qty = Integer.valueof(params[0]);
        String accountId;
        if(params != null && params.size()>0){
            accountId = params[0];
        }
        System.debug('accountid======>'+accountId);
        List<Opportunity> opportunities = new List<Opportunity>();
        if(accountId != null){
            Account acc = [select Name from Account where Id = :accountId];
            List<Account_Plan__c> accountPlanList = [select Id, Annual_Revenue__c, Average_Outstanding__c, ROEC_Return_on_Economic_Capital__c,
                                                     RORC_Return_on_Regulatory_Capital__c,All_In_Drawn_Spread_LIBOR_Spread_Faci__c,
                                                     Commitment_Amount__c from Account_Plan__c where Account__c =: accountId and Status__c = 'Active'];
            List<Customer_Need_Analysis__c> needAnalysisList = [select Id, Name, Product_Name_X__r.Name, Service_Provider__c, Services_Used__c,
                                                                Actual_Revenue__c, Future_Opportunity__c, Share_of_Wallet_estimate__c, RM_Estimate__c,
                                                                Comments__c, Opportunity_Created__c from 
                                                                Customer_Need_Analysis__c where Product_Name_X__c in : accountPlanList];
            for(Customer_Need_Analysis__c cna : needAnalysisList){
                if(!cna.Opportunity_Created__c){
                    cna.Opportunity_Created__c = true;
                    Opportunity opp = new Opportunity(Name = acc.Name+' - '+cna.Name+' - FY 17', Amount__c = cna.Actual_Revenue__c,
                                                     AccountId = accountId, closeDate = System.today().addDays(15),
                Start_Date__c = System.today().addDays(30),
                End_date__c = System.today().addDays(395),
                Product__c = 'Loans',
                stageName = 'Prospecting');
                    opportunities.add(opp);
                }
            }
            insert opportunities;
            update needAnalysisList;
        }
        List<BotRecord> records = new List<BotRecord>();
        
        for (Opportunity o : opportunities) {
            List<BotField> fields = new List<BotField>();
            fields.add(new BotField('Name', o.Name, '#/sObject/' + o.Id + '/view'));
            fields.add(new BotField('Amount', '$' + o.Amount__c));
            fields.add(new BotField('Stage', o.StageName));
            records.add(new BotRecord(fields));
        }
        if(opportunities.size() == 0){
             return new BotResponse(new BotMessage('Bot', 'Opportunities have already been created for existing Need Analysis records', records));
        }
        return new BotResponse(new BotMessage('Bot', 'Created ' + opportunities.size() + ' opportunities:', records));
    }
}