src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assets_Under_Management__c</fullName>
        <label>AUM</label>
        <summarizedField>Deposit__c.Current_Balance__c</summarizedField>
        <summaryForeignKey>Deposit__c.Account_Name__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Retention_Risk__c</fullName>
        <label>Retention Risk</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Risk_Factor__c</fullName>
        <label>Risk Factor</label>
        <picklist>
            <picklistValues>
                <fullName>Large Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint to RM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M&amp;A activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_AUM__c</fullName>
        <formula>AUM_Loans__c+Assets_Under_Management__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total AUM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Tax_Returns__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Tax Returns</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Capital_Allocation_and_Approvals__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Capital Allocation and Approvals</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insurance_Certificate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Insurance Certificate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_Reports__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Property Reports</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax_Assessment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tax Assessment</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FX</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FX</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Product Manager - Commercial Lines/Rate Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager - Money Market/Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager - Real Estate/Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager - Commercial Term Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Service Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/RelatedListController.cls
public with sharing class RelatedListController {
    
    @AuraEnabled 
    public static List<Account> getAccounts(){
        //Check for ownerId for Custom : Relationship Manager profile
        if(UserInfo.getProfileId().containsIgnoreCase(Label.RM_profile_id)){
            return [SELECT Id, Name,Phone,Assets_Under_Management__c, risk_factor__c, Industry,Retention_Risk__c,AnnualRevenue,Total_AUM__c FROM Account where ownerId = :UserInfo.getUserId() ORDER BY Total_AUM__c DESC LIMIT 4];
        }else{
            return [SELECT Id, Name,Phone,Assets_Under_Management__c, risk_factor__c, Industry,Retention_Risk__c,AnnualRevenue,Total_AUM__c FROM Account ORDER BY Total_AUM__c DESC LIMIT 4];
        }
    }
    @AuraEnabled 
    public static List<Opportunity> getTopOpportunities(){
        //Check for ownerId for Custom : Relationship Manager profile
        if(UserInfo.getProfileId().containsIgnoreCase(Label.RM_profile_id))
            return [SELECT Id, Name, Account.Name, Amount,Amount__c, StageName, CloseDate FROM Opportunity where StageName !='Closed Won' AND StageName !='Closed Lost' AND Account.ownerId = :UserInfo.getUserId() ORDER BY Amount__c DESC LIMIT 3];
        else
            return [SELECT Id, Name, Account.Name, Amount,Amount__c, StageName, CloseDate FROM Opportunity where StageName !='Closed Won' AND StageName !='Closed Lost' ORDER BY Amount__c DESC LIMIT 3];
    }
    
    @AuraEnabled 
    public static List<Account> getGrowthClientList(){
        //Check for ownerId for Custom : Relationship Manager profile
       if(UserInfo.getProfileId().containsIgnoreCase(Label.RM_profile_id))
            return [SELECT Id, Name,Phone,Assets_Under_Management__c,Total_AUM__c,Retention_Risk__c,Risk_Factor__c FROM Account where Retention_Risk__c='High' AND ownerId = :UserInfo.getUserId() ORDER BY Total_AUM__c DESC LIMIT 3];
        else
            return [SELECT Id, Name,Phone,Assets_Under_Management__c,Total_AUM__c, Retention_Risk__c,Risk_Factor__c FROM Account where Retention_Risk__c='High' ORDER BY Total_AUM__c DESC LIMIT 3];
    }
    
    @AuraEnabled
    public static List<ListView> getListViews() {
        List<ListView> listviews =  [SELECT Id, Name FROM ListView WHERE SobjectType = 'Account' and Name='Top Accounts'];
        return listviews;
    }
    
    @AuraEnabled
    public static List<ListView> getOpptyListViews() {
        List<ListView> listviews =  [SELECT Id, Name FROM ListView WHERE SobjectType = 'Opportunity' and Name='Top Opportunities'];
        return listviews;
    }
    
    @AuraEnabled 
    public static List<OpportunityLineItem> getTopProducts(){
        return [SELECT Id, Product2Id, Product2.Name, Opportunity.name, Type__c, Opportunity.Amount,Opportunity.Amount__c, Fee__c FROM OpportunityLineItem where Type__c != null AND Fee__c != null ORDER BY Opportunity.Amount__c DESC LIMIT 3];
    }
    
     @AuraEnabled 
    public static List<Opportunity> getTopOpportunitiesForService(){
        //owner is hardcoded to Bruce Edwards
        return [SELECT Id, Name, Account.Name, Amount,Amount__c, StageName, CloseDate FROM Opportunity where StageName ='Closed Won' AND (Insurance_Certificate__c = false OR Property_Reports__c = false 
                OR Tax_Assessment__c= false OR Capital_Allocation_and_Approvals__c = false OR Business_Tax_Returns__c = false)  AND Account.OwnerId =: UserInfo.getUserId() ORDER BY Amount DESC LIMIT 3];
    }
    
    @AuraEnabled
    public static User getCurrentUser() {
      User user = [SELECT Id, FirstName, LastName, Role__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
      return user;
  }
  }