src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_date__c</fullName>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Derivatives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cards</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreateRecordFromBot.cls
@RestResource(urlMapping='/createOpportunity/*')
global with sharing class CreateRecordFromBot {

    @HttpGet
    global static String doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        return UserInfo.getSessionId();
    }
  
    @HttpPost
    global static String doPost(String accountId, String productName, String endDate, Integer amount) {
        try{
            Account acc  = [select Name from Account where Id = :accountId];
            Opportunity oppty = new Opportunity(
                Name = acc.Name +' - '+productName +' - FY 17',
                AccountId = accountId,
                closeDate = Date.valueOf(endDate),
                Start_Date__c = Date.valueOf(endDate).addDays(30),
                End_date__c = Date.valueOf(endDate).addDays(395),
                Product__c = 'Loans',
                stageName = 'Prospecting',
            Amount__c = Decimal.valueOf(amount));
            insert oppty;
            return 'Opportunity has been created. Name: '+oppty.Name;
        }catch(Exception ex){
            return 'Error while creating an Opportunity. Error Message: '+ex.getMessage();
        }
        return 'Error in rest call';
    }
}